import links from "../../shared/links.json";

export const data = {
  title: "تخلص من آلامك وابدأ رحلة التأهيل مع أمين",
  symptoms: [
    {
      id: 0,
      active: false,
      style: "head",
      name: "head",
      arName: "الاضطرابات العصبية",
      description: "اعمل على تحسين مشاكل حركتك",
    },
    {
      id: 1,
      active: false,
      style: "nek",
      name: "nek",
      arName: "آلام الرقبة",
      description: "اكتسب القدرة على الحركة والتخلص من الآلام",
    },
    {
      id: 2,
      active: false,
      style: "shoulder",
      name: "shoulder",
      arName: "آلام الكتف",
      description: "اكتسب القدرة على الحركة الحرّة للتحرك واللعب",
    },
    {
      id: 3,
      active: false,
      style: "elbow",
      name: "elbow",
      arName: "آلام الكوع",
      description: "الانحناء والتقويم والرفع بحرية",
    },
    {
      id: 4,
      active: false,
      style: "hand",
      name: "hand",
      arName: "آلام اليد ",
      description: "احصل على قدر أكبر من الحركة والمرونة",
    },
    {
      id: 5,
      active: false,
      style: "back",
      name: "back",
      arName: "آلام الظهر",
      description: "قم باللف والرفع والانحناء بحرية",
    },
    {
      id: 6,
      active: false,
      style: "hip",
      name: "hip",
      arName: "آلام الورك",
      description: "بناء القدرة على الحركة للاستمتاع بالمشي في الخارج",
    },
    {
      id: 7,
      active: false,
      style: "knee",
      name: "knee",
      arName: "آلام الركبة",
      description: "اجلس ، وقف، وتحرك بثقة",
    },
    {
      id: 8,
      active: false,
      style: "ankle",
      name: "ankle",
      arName: "آلام الكاحل",
      description: "تعافي من الإصابات و تحرك بحرية",
    },
    {
      id: 9,
      active: false,
      style: "foot",
      name: "foot",
      arName: "آلام القدم",
      description: "اكتسب خفة الحركة لتحقق توازن أفضل",
    },
    {
      id: 10,
      arName: "والمزيد ...",
    },
  ],
  button: {
    href: links.booking.link,
    title: "احجز الآن!",
  },
};
